name: Pull Request Template
description: Create a pull request for code changes
title: "[Feature/Improvement/Bug Fix]: <Summary of change>"
labels: [ "pull request" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a pull request to Consul.NET! Please provide the following information to help us review and merge your changes effectively.

  - type: textarea
    id: description-of-changes
    attributes:
      label: Description of Changes
      description: A clear and concise description of the changes made in this pull request
      placeholder: |
        Describe the main changes made in this PR.
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: List any related issues, if applicable, using the format `#issue_number`
      placeholder: |
        #123
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any additional context or information about this pull request
    validations:
      required: false
