version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the `root` directory
    directory: "/"
    # Check the nuget registry for updates every day (weekdays) schedule:
    interval: "daily"
