image:
  file: .gitpod.Dockerfile

# Adding vscode C# extension
vscode:
  extensions:
    - muhammad-sammy.csharp

# Ports to expose
ports:
  - name: Consul Dev Server UI
    port: 8500
    onOpen: open-preview

# Start-up tasks
tasks:
  - name: .NET platform
    before: |
      dotnet --version
    init: |
      dotnet build
    command: |
      dotnet run
  - name: Consul Server
    before: |
      consul --version
    command: |
      cd Consul.Test/
      consul agent -dev -config-file test_config.json
    openMode: split-right

# TODO: customize pre-builds
# Configuring pre-builds
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

# TODO: providing a demo using GitPod => add Samples/ in same repository that can be run in the same workspace
