image: gitpod/workspace-dotnet:latest

vscode:
  extensions:
    - muhammad-sammy.csharp

## List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Consul Dev Server
    port: 8500
    onOpen: open-preview

## List the start-up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
#tasks:
#  - init: echo 'init script' # runs during prebuild
#    command: echo 'start script'
tasks: # TODO: update this to install Consul + Build project ?? (check with J.)
  - name: Restore & Build
    init: |
      dotnet dev-certs https
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run


# TODO: providing a demo using GitPod => add Samples/ in same repository that can be run in the same workspace
